baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Welcome to my website!"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Raysa DÃ­az"
  namecolor: ffc107
  profession: "Sociologist"
  github: "https://github.com/raysamariana24"
  linkedin: "https://www.linkedin.com/in/raysa-diaz-romero-a335b4206/"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hello! I am Raysa, a bachelor in Sociology from Pontifical Catholic University of Peru. I consider myself very proactive, responsible, disciplined and motivated to continue learning. I am currently working as a teaching assistant of academic research at PUCP."
  descripe_l2_person: "My interests topics are rural development, gender, environment, programming and statistics. Knowledge acquired in managing interviews and databases."
  skills:
    - name: Rstudio
      percentage: 85
    - name: SPSS
      percentage: 80
    - name: Python
      percentage: 75
    - name: Machine Learning
      percentage: 75

  # Experience
  disable_experience: false
  experience:
    - company: "Pontifical Catholic University of Peru"
      role: "Teaching assistant of Academic Research"
      startdate: Feb 2022
      enddate: present

    - company: "Marketing JH"
      role: "Editor"
      startdate: Jul 2021
      enddate: Dec 2021
      featuredpoints:
        - point: Writing opinion articles on websites
    - company: "GWS PERU SAC"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "English teacher"
      startdate: Mar 2018
      enddate: Dec 2018
      featuredpoints:
        - point: Improve the comprehension and increase the vocabulary of the students
        - point: Perform dynamics and participation through the use of materials for better student learning.

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
